### ISSUE TITLE
Error message: void-function all-the-icons-icon-family

### ISSUE THREAD

**Issue by joncol** [domtronn/spaceline-all-the-icons.el#10]
Hi again,

For some files I get the following error message (and a blank status line):

`Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (void-function all-the-icons-icon-family) [9 times]`

This happened for my .org file containing my task list.

**Comment by domtronn** [comment]
You need *v2.4.1* of [`all-the-icons.el`](https://github.com/domtronn/all-the-icons.el), that was a new function added in that patch version.

If you update the package this should fix it :)

**Comment by joncol** [comment]
Is that not on melpa? I got the 2017-04-10.114 build from melpa.

**Comment by joncol** [comment]
Nevermind, actually *updating* the package list and then installing the latest melpa package solved this.

**Comment by domtronn** [comment]
As a side, I've added some shields which should tell people the latest versions on Melpa. Glad that worked for you though! 👍
