### ISSUE TITLE
error during redisplay: void-variable mode-line

### ISSUE THREAD

**Issue by Vonfry** [domtronn/spaceline-all-the-icons.el#100]
Recently, spaceline-all-the-icons cannot work for me. I have tried to track why it is, but failed. 

If I disable this package, my emacs can work correctly. I have tried to test only with spaceline and spaceline-all-the-icons by only loading the two packages with `emacs -q`, and the issue is same.

output by `spaceline-all-the-icons--debug-segments`
```
Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (void-variable mode-line) [62 times]
spaceline-all-the-icons--debug-segments:  Errors found in Spaceline Segments: [battery-status, buffer-id, buffer-path, buffer-size, eyebrowse-workspace, flycheck-status-info, flycheck-status, git-status, hud, mode-icon, modified, multiple-cursors, narrowed, neotree-close-bracket, neotree-context, neotree-dirs, neotree-files, neotree-index, neotree-open-bracket, nyan-cat, org-clock-current-task, package-updates, paradox-filter, paradox-line-count, paradox-status-installed, paradox-status-new, paradox-status-upgrade, paradox-total, position, process, projectile, region-info, separator-left-active-1, separator-left-active-2, separator-left-active-3, separator-left-active-4, separator-left-extra-1, separator-left-extra-2, separator-left-inactive, separator-minor-mode-left, separator-minor-mode-right, separator-paradox-1, separator-paradox-2, separator-paradox-3, separator-paradox-4, separator-right-active-1, separator-right-active-2, separator-right-inactive, sunrise, sunset, temperature, time, vc-icon, vc-status, weather, which-function, window-number]
```

**Comment by ekaschalk** [comment]
Quoting the faces after each `:face` in the calls to `spaceline-compile` in `spaceline-all-the-icons.el` was a sufficient fix for me.

**Comment by boothead** [comment]
This was how I fixed it: https://github.com/syl20bnr/spacemacs/issues/11784#issuecomment-452633754

Hopefully once the fix you mention is deployed I can roll my changes back.

**Comment by hexmode** [comment]
This issue should be re-opened until a fix is actually merged.  I have a fix that doesn't involve pinning that I'm about to create a pull request for.

**Comment by mjgiarlo** [comment]
@hexmode are you still planning to submit a PR for this? @Vonfry are you inclined to consider said PR?

Thanks, all.

**Comment by hexmode** [comment]
@mjgiarlo thanks for the nudge.  I thought I had a pull request already.  I think @domtronn has to merge it, though, not @Vonfry.
