### ISSUE TITLE
Clock Icon should only be included in Fullscreen Frames

### ISSUE THREAD

**Issue by domtronn** [domtronn/spaceline-all-the-icons.el#12]
_(Quoted from @jwintz #7)_
> the clock icon: I used to use your fonts, with the awesome all-the-icons in my previous setup in various places but since I didn't plan on getting weather forecast in my editor, I skipped the weather once. Now it is fixed, and I have my beautiful clock, however, I think this segment should only be display when the current frame is fullscreen.

**Comment by domtronn** [comment]
I'm not sure why you would want this behaviour? Would you mind adding some justification for this?
Is it more that you would only want the clock when in you only have one window horizontally?

I mean, I can always add some kind of custom variable/setting for this 🤔

**Comment by jwintz** [comment]
No, my point is that this information is redundant with any desktop environment (which always displays current time), whenever emacs is not fullscreen. However, with a fullscreen emacs, the desktop environment panels are not visible anymore ;-)

**Comment by domtronn** [comment]
Ah! That's a very good point 😅  However, on my mac I have the _"Automatically hide and show the menu bar"_ enabled, so even when Emacs _isn't_ fullscreen I can't see the time!

<img width="780" alt="screen shot 2017-04-21 at 12 24 36" src="https://cloud.githubusercontent.com/assets/5881414/25275498/82b3bb4e-268d-11e7-9884-7762de51ca1c.png">

But yep, that's a good enough reason for me to make this a customisable feature, I'll start working on this now 👍

**Comment by jwintz** [comment]
Awesome :-)

**Comment by jwintz** [comment]
Works like a charm, whenever used with the `spaceline-all-the-icons-fullscreen` segment. The behaviour is random using MacOS maximise button.

**Comment by jwintz** [comment]
Actually, using the MacOS green traffic light button, the behaviour is inversed (clock shows on minimize, disappears on maximize).

**Comment by domtronn** [comment]
Hmm, I can't reproduce this behaviour with the traffic light butotn? Is this still an issue?
