### ISSUE TITLE
Text Scale segment throwing error

### ISSUE THREAD

**Issue by domtronn** [domtronn/spaceline-all-the-icons.el#16]
_(Quoted from @jwintz #7)_
> text-scale works fine whenever you increase or decrease the text scale. By default the modeline does not render anything with the following message: Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (void-variable text-scale-mode-lighter) [36 times]

**Comment by jwintz** [comment]
Great ! Thanks !
