### ISSUE TITLE
Window Numbering error when using Square Icon Set

### ISSUE THREAD

**Issue by domtronn** [domtronn/spaceline-all-the-icons.el#17]
_(Quoted @jwintz #7)_
>using `(setq spaceline-all-the-icons-icon-set-window-numbering (quote square))`, breaks the modeline rendering when window number exceeds one: `Invalid face attribute :background nil Invalid face attribute :foreground nil Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (wrong-type-argument listp (:height 1.2 :inherit)) [24 times]`

**Comment by domtronn** [comment]
I can't seem to reproduce this for windows greater than one? _(see the below screenshot)_
<img width="1348" alt="screen shot 2017-04-21 at 10 12 32" src="https://cloud.githubusercontent.com/assets/5881414/25271170/1a3ec85e-267b-11e7-869d-99f099af1098.png">

_However_, it does seem to throw errors when the window numbers reach 10, I'll look into a fix for this :)

**Comment by jwintz** [comment]
Just updated all of my melpa packages, including `all-the-icons` and `spaceline-all-the-icons` but the issue remains.

![screen shot 2017-04-21 at 11 39 07](https://cloud.githubusercontent.com/assets/3277054/25272201/4c1390d8-2687-11e7-9f8b-90451f1dc508.png)

Forks fine with other `spaceline-all-the-icons-set-window-number-values` though :-(

**Comment by jwintz** [comment]
Reinstalled `material-icon` just to be sure and played with `all-the-icons-window-number`.

```
Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (wrong-type-argument listp (:height 1.2 :inherit)) [16 times]
```

It comes from https://github.com/domtronn/spaceline-all-the-icons.el/blob/master/spaceline-all-the-icons-segments.el#L374-L398 where `plist-put` has wrong argument type.

Removing these two lines, I get the expected result !

Before:

<img width="1540" alt="screen shot 2017-04-21 at 19 09 09" src="https://cloud.githubusercontent.com/assets/3277054/25288734/f57ef664-26c6-11e7-9dab-55723a7148d8.png">

After:

<img width="1388" alt="screen shot 2017-04-21 at 19 14 53" src="https://cloud.githubusercontent.com/assets/3277054/25288750/0a5453cc-26c7-11e7-86fc-40184861f6c0.png">

Do you mind a PR ?

**Comment by domtronn** [comment]
Hmm, I don't think this is the expected behaviour though...  😞 

You need the `plist-put ... :family`  in order to set the correct font family to display the icon with, otherwise you run the risk of the system choosing some other unicode character instead of the `material-design` icon.

I'm not sure why it won't let you do the `plist-put` though? What result do you get when you call

```el
(plist-put '(:height 1.0 :inherit) :family "foo")
```

It shouldn't error and should return...

```el
(:height 1.0 :family "foo" :inherit)
```

**Comment by jwintz** [comment]
Completely agree with you ! Just trying to isolate the bug.

Here is the result using `C-x C-e` in the scratch buffer. At least it is consistent with the previous one ;-)

<img width="684" alt="screen shot 2017-04-21 at 19 31 55" src="https://cloud.githubusercontent.com/assets/3277054/25289299/483ed520-26c9-11e7-8541-8e093e3833d1.png">

**Comment by domtronn** [comment]
That's weird! It works for me 😅 What version of Emacs do you use and what's the result when you `(describe-function 'plist-put)`?

The alternative would be to replace the `plist-put`s with `(setq face (append face '(:family ...)))`, much more verbose, but achieves the same thing :/ 

But you're right, it'd be nice to understand/isolate why this is happening

**Comment by jwintz** [comment]
As shown in the screenshot: 26.0.50. `describe-function` doesn't complain. I do not understand the behaviour then. My emacs-lisp fu is awful, but it seems like a syntax error when it comes to quoting the lists or so ...

<img width="1444" alt="screen shot 2017-04-21 at 19 37 31" src="https://cloud.githubusercontent.com/assets/3277054/25289495/1eb1ecaa-26ca-11e7-8e9b-fb0fcb1c1846.png">

**Comment by domtronn** [comment]
Interesting.. I'm still on Emacs 25.1, I'm going to install a copy of `emacs-plus` mentioned in your Prolusion ReadMe - Maybe they've changed the implementation/definition of `plist-put`?

That way I can confirm if it's the Emacs Version that's the problem 🙂 I'll let you know shortly 👍

**Comment by jwintz** [comment]
Looks like the list isn't changed _in place_, and that the result should be reafected. What about your `plist-put` description ? What about your emacs version ?

**Comment by jwintz** [comment]
I've looked for deprecation, but nothing is mentioned. Quite surprising for emacs API.

**Comment by domtronn** [comment]
I can't install `emacs-plus` because my XCode is out of date, and I can't upgrade it on this Mac at the moment... 😒 So yeah, I'd be happy with a PR to swap the `plist-put` for `append`, or I can pick it up later/tomorrow?

**Comment by jwintz** [comment]
There are 10 occurrences of `plist-put`. I can try and update them all (since my anaux-mode is working now ;-)).

Should I update them all ?

**Comment by jwintz** [comment]
And by the way, according to https://www.gnu.org/software/emacs/manual/html_node/elisp/Plist-Access.html, wouldn't it be more appropriate to `setq face` instead of using `append` ?

**Comment by domtronn** [comment]
That would be great if you've got time, otherwise I'll pick this up when I get some time tomorrow.

And yes, you'll need to do both... Because the `setq` isn't going to stop the error you're getting with incorrect argument type listp, so I would suggest changing all `plist-put` calls from

```el
(plist-put 'face :property val)
;; to
(setq face (append '(:property val) 'face))
```

Bear in mind, that for values that need to be _computed_ _i.e._ with a function call, you'll need to use backticks and commas to denote a list that has elements that need evaluating, for example

```el
(setq face (append `(:family ,(all-the-icons-material-family)) 'face))
```
