### ISSUE TITLE
Git branch segment

### ISSUE THREAD

**Issue by jwintz** [domtronn/spaceline-all-the-icons.el#19]
Hi Dom,

I have both:

```emacs-lisp
  (spaceline-toggle-all-the-icons-vc-status-on)
  (spaceline-toggle-all-the-icons-git-status-on)
  (spaceline-toggle-all-the-icons-vc-icon-on)
```

But there is no way for me to get the current branch name as a segment, even though additions and deletions show up just fine.

**Comment by domtronn** [comment]
What version control are you using? Git?
Could you please print the value of `vc-mode`?

**Comment by jwintz** [comment]
Yes, git, mostly. Evaluating `vc-mode` does not provide pertinent information.

**Comment by domtronn** [comment]
That's odd... `vc-mode` is a native variable and Emacs should detect this for you... Did the original `spaceline` theme contain information for the branch? I can't see anything in [`spaceline-segments.el`](https://github.com/TheBB/spaceline/blob/master/spaceline-segments.el) that uses/displays it. 🤔 

I also don't think I have to do anything to set `vc-mode` up in my init. 

Here's some [docs](https://www.gnu.org/software/emacs/manual/html_node/emacs/Version-Control.html) on `vc-mode` and Emacs, but I'm not sure if they're useful.

**Comment by jwintz** [comment]
Again, my bad. Some snippets of my previous modeline setup were messing things around. By removing it it works just fine. Sorry for the noise :-(

![screen shot 2017-04-21 at 15 15 07](https://cloud.githubusercontent.com/assets/3277054/25279056/8f56b56e-26a5-11e7-932b-6bd0e77b6af5.png)

**Comment by domtronn** [comment]
Ah, well glad it's working for you!

**Comment by jwintz** [comment]
Thanks and congratulations for the awesome job !
