### ISSUE TITLE
Huge powerline height by default

### ISSUE THREAD

**Issue by bricewge** [domtronn/spaceline-all-the-icons.el#3]
By default the powerline-height is set to 22 on spacemacs. Setting it back to 1 solve this but if this theme would have a good default for it this will be great.
![screen shot 2017-04-14 at 10 11 21](https://cloud.githubusercontent.com/assets/5525646/25038060/eed9253e-20fc-11e7-89ec-a6455a869a4f.png)

**Comment by domtronn** [comment]
Powerline doesn't set a height by default _(see [here](https://github.com/milkypostman/powerline/blob/master/powerline.el#L95-L98))_. However, it seems like [`Spacemacs` does](https://github.com/syl20bnr/spacemacs/blob/master/core/core-fonts-support.el#L86-L90)...

Looks like I had a different understanding for what `powerline-height` means 😅 I saw it as a scaling factor, _i.e._ a value of 2 would double the size of the mode line.

And it looks like when propertizing a text's height, the behaviour changes based on whether the value is an integer/float. When given a float _(which is what I do for all my segments)_ it will _scale_ the size of the font based on the size of the underlying font face _(which all inherit from default font size)_ as documented [here](https://www.gnu.org/software/emacs/manual/html_node/elisp/Face-Attributes.html). Unfortunately, this means we're both right! 

Buuuut, there is a variable called `powerline-text-scale-factor` which seems to be the intended version of what I want so I'm going to swap over to using that.
