### ISSUE TITLE
Requesting help installing in spacemacs

### ISSUE THREAD

**Issue by teesloane** [domtronn/spaceline-all-the-icons.el#31]
EDIT: Figured it out!

I just had to run `SPC SPC configuration-layer/update-packages. 

Leaving this here for ...posterity? Helping any others who might be in the same boat...

***

Hello, hello!

I stumbled across your spaceline tonight and it looks awesome. I've spent about the last 1.5 hours getting it to work with my `spacemacs` and I'm feeling like perhaps I've got something in my .spacemacs that could be conflicting with it. If you have time to lend a hand that would be great!

Here's what I've tried.

- `SPC SPC Package install` -> search for your package and install it (both all-the-icons and spaceline-all-the-icons).
- add your packages to my `additional packages like so:

```lisp
   dotspacemacs-additional-packages '(js-import centered-window-mode all-the-icons spaceline-all-the-icons base16-theme)
```

- `SPC SPC spaceline-all-the-icons-theme` (see screenshot)
<img width="443" alt="screenshot 2017-05-12 23 59 31" src="https://cloud.githubusercontent.com/assets/12987958/26022283/183277cc-376f-11e7-89ec-018d1c4c6ffe.png">

---
so None of the above seemed to work for me, so I also just tossed this from your readme into my `user-config`

```
  (package-install 'spaceline-all-the-icons)

  (require 'spaceline-all-the-icons)
  (use-package spaceline-all-the-icons
    :after spaceline
    :config (spaceline-all-the-icons-theme))

```
but at this point I have no idea what I'm doing!

Thanks for any help, and let me know if I can provide any more information. 

👍

**Comment by domtronn** [comment]
Thanks for all this info @teesloane! I don't use Spacemacs personally, so this is really helpful!

I'll look at adding this to the `README.md` to help others, but I'll leave this issue here for now, like you say, to help others 🙂

**Comment by franksn** [comment]
You can try adding new layer and write this in the packages.el (using spacemacs-base for example):

    (defconst my-spaceline-packages
      '(all-the-icons
        spaceline
        spaceline-all-the-icons))

    (defun my-spaceline/init-all-the-icons ()
        (use-package all-the-icons
          :config (setq neo-theme 'icons)))

    (defun my-spaceline/init-spaceline ()
       (use-package spaceline))

    (defun my-spaceline/init-spaceline-all-the-icons ()
        (use-package spaceline-all-the-icons
          :after spaceline
          :config (progn
                    (spaceline-all-the-icons-theme)
                    (spaceline-all-the-icons--setup-package-updates)
                    (spaceline-all-the-icons--setup-git-ahead)
                    (spaceline-all-the-icons--setup-neotree)
                    (setq spaceline-all-the-icons-separator-type 'slant))))

Correct me if any of you found a better way.

**Comment by teesloane** [comment]
Closing this as I figured it out!

**Comment by itome** [comment]
@teesloane 
Hi! I'm now trying to use this package in spacemacs.
I installed this package by adding to `dotspacemacs-additional-packages`.
I added this in `dotspacemacs/user-config`
```
  (use-package spaceline-all-the-icons
    :after spaceline
    :config (spaceline-all-the-icons-theme))
```
And Run `SPC SPC configuration-layer/update-package`
But not worked correctly.
Did you do something other than I write here? Any ideas would be appreciated!!

**Comment by CarlQLange** [comment]
in case you're wondering, @franksn's solution works perfectly.

1. run `SPC SPC configuration-layer/create-layer`
2. select the private directory (or whatever dir you want)
3. name it `my-spaceline` or whatever you want
4. paste the following into the opened `packages.el`

```elisp
(defconst my-spaceline-packages
  '(all-the-icons
    spaceline
    spaceline-all-the-icons))

(defun my-spaceline/init-all-the-icons ()
    (use-package all-the-icons
      :config (setq neo-theme 'icons)))

(defun my-spaceline/init-spaceline ()
   (use-package spaceline))

(defun my-spaceline/init-spaceline-all-the-icons ()
    (use-package spaceline-all-the-icons
      :after spaceline
      :config (progn
                (spaceline-all-the-icons-theme)
                (setq spaceline-all-the-icons-separator-type 'slant))))
```

Great job @franksn!
