### ISSUE TITLE
Add custom segments with callback

### ISSUE THREAD

**Issue by frapples** [domtronn/spaceline-all-the-icons.el#32]
I want to add a segments displaying file encoding:
```
  (spaceline-all-the-icons-theme 'file-encoding
                                 (lambda () (format "%s" buffer-file-coding-system))
                                 'etc)
```
But the code can not work.

But I try:
```
 (spaceline-all-the-icons-theme 'file-encoding
                                 (lambda () "hello")
                                 'etc)
```
Work well.

**Comment by domtronn** [comment]
Segments need to be defined as a mode line evaluation string, so [Spaceline](https://github.com/TheBB/spaceline#turning-segments-on-and-off) comes with some segments predefined, which can be called, for example

```el
(spaceline-all-the-icons-theme 'buffer-encoding)
```

Otherwise, you want an eval expression, like

```el
(spaceline-all-the-icons-theme '("%e" (:eval (format "hello %s"))))
```

Hope this helps 🙂

**Comment by frapples** [comment]
Thank you! :smile:
