### ISSUE TITLE
Time is displayed, but not date

### ISSUE THREAD

**Issue by publicimageltd** [domtronn/spaceline-all-the-icons.el#42]
I hope I am not missing something obvious, but I am unable to display the date in the modeline. I have turned on `display-time-mode`:

```
(display-time-mode 1)
(setq display-time-day-and-date t)
```

...but all I see is the time. Am I missing something obvious? Other themes (like `powerline-default-theme`) display the date nicely.

**Comment by domtronn** [comment]
Hey @publicimageltd, Just had a brief look at this and found that the way Powerline handles the time stuff is through the `global-mode-string` - This is a list of variables that take global precedence in the mode line! And enabling `display-time-mode` adds `display-time-string` to those list of variables.

However, the segment in `spaceline-all-the-icons` just uses the `format-time-string` function but it would be much better if it used the `display-time-string` when present! 

I'll add this in when I get some time 👍

**Comment by domtronn** [comment]
@publicimageltd This should now be available in version [`1.3.3`](https://github.com/domtronn/spaceline-all-the-icons.el/releases/tag/1.3.3) of the package, give it a bit of time to build up to Melpa but it should be there by the end of the day :)

**Comment by publicimageltd** [comment]
Thank you, both for the fast reply and the patch!

**Comment by publicimageltd** [comment]
Finally installed the new version. O how beautiful, it even has a nice icon! :-) Perfect!

**Comment by domtronn** [comment]
Haha, glad you like it! I'd be remiss if I don't add in icons anywhere and everywhere possible!

If you have any other suggestions or ideas, please feel free to raise more issues or PRs :)
