### ISSUE TITLE
Failure to render when git status has changes

### ISSUE THREAD

**Issue by ieei** [domtronn/spaceline-all-the-icons.el#43]
```
Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (error "Unknown upattern `(quote deleted)'") [9 times]
QuitError during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (error "Unknown upattern `(quote deleted)'")
```

I'm unable to insert the `deleted` icon with `all-the-icons-insert` as well. If that matters?

**Comment by ieei** [comment]
However, using `customize-group` it looks like it should use the diff icons, which there shows perfectly.

**Comment by domtronn** [comment]
Ah yeah! It's my use of `pcase`

Apparently there are a few different behaviours on different emacs versions for matching simple symbols! I should probably be using `cl-case` instead. I'll get a fix in for this :)
