### ISSUE TITLE
battery face

### ISSUE THREAD

**Issue by mclearc** [domtronn/spaceline-all-the-icons.el#45]
I'd like the fancy-battery face to use different colors than the default (I'm using the solarized color theme). The following worked for my old spaceline cofig:

``` emacs-lisp
 (use-package fancy-battery
    :init 
    (fancy-battery-mode)
    :config
    (setq-default battery-update-interval 10)
    (set-face-attribute 'fancy-battery-charging nil 
    :foreground "dark blue" :weight 'bold)
    (set-face-attribute 'fancy-battery-discharging nil 
    :foreground "dark magenta" :weight 'bold)
    (set-face-attribute 'fancy-battery-critical nil 
    :foreground "dark red" :weight 'bold))

```

But this doesn't seem to be working with spaceline-all-the-icons. Any ideas?

**Comment by domtronn** [comment]
Hey! I didn't realise that `fancy-battery` exposed it's own faces, makes complete sense 🙂 

By default, the just inherit from the faces I chose to use anyway! So I've refactored this to inherit from these faces instead. _Once this gets built_, this should hopefully fix it for you.

If you could try out the new version and report back, that would be great! Thanks

**Comment by mclearc** [comment]
Great - that works. Thanks for the package and the quick response!
