### ISSUE TITLE
nyan-mode segment

### ISSUE THREAD

**Issue by pqhieu** [domtronn/spaceline-all-the-icons.el#48]
Hi,

First, thank you for the work. This mode line theme is awesome!
However I didn't see any [nyan-mode](https://github.com/TeMPOraL/nyan-mode) segment in the source code. Is it currently not supported?

Do you have any plans to include a nyan-mode segment into this theme any time soon?

Cheers,

**Comment by domtronn** [comment]
Hey! It's not a segment I use personally so I probably just never got round to adding it 😅 
If it's something you'd like, I'm more than happy to add one in?
In that case I can convert this issue into a feature request

**Comment by pqhieu** [comment]
Wow, thanks a lot, I would be more than happy if it's added. 
Keep up the good work!

**Comment by domtronn** [comment]
@pqhieu I've just pushed a version of `spaceline-all-the-icons` with the lovely nyan cat segment back in! 👍 

It's enabled by default if you have `nyan-mode` on and will appear in the centre of the mode line, let me know if you have any troubles with it or would like anything different! 🙂

**Comment by pqhieu** [comment]
@domtronn Thanks for the work. It's working great!

However I think I found a bug in your code that causes Emacs to spew lots of ```Invalid face reference``` messages. You can check the ```*Messages*``` buffer when performing cursor movement to see it. See my PR for the fix.

Another thing I would like to see is to have a separator at the right hand side of the nyan segment.
Since without it I don't know where is the end of the buffer. Here is an comparison with ```spaceline```.
<img width="1280" alt="screen shot 2017-07-10 at 10 36 46 pm" src="https://user-images.githubusercontent.com/3043830/28030503-a5c8dc6c-65d6-11e7-8748-daaa9d5a8a91.png">
and yours (see that I'm at the end of the buffer but the cat is not, lol).
<img width="1280" alt="screen shot 2017-07-11 at 1 22 15 am" src="https://user-images.githubusercontent.com/3043830/28030845-f98a3a48-65d7-11e7-91ba-3a667bd8cea5.png">

I have also made some modifications to add a new separator at the end of nyan segment to make it look like this
<img width="1280" alt="screen shot 2017-07-11 at 1 32 09 am" src="https://user-images.githubusercontent.com/3043830/28031105-d7f4156a-65d8-11e7-8a7d-e1d7b9de6726.png">

What do you think? I'm not good with styling, so this is just a quick fix. If you're interested then I will create a PR.

Cheers,

**Comment by domtronn** [comment]
Yep! Very much see your point about having Nyan cat delimited by something so you can tell where abouts in the buffer you are! I've updated the segment to reflect your designs - Just there are some nuances around showing/not showing it so hopefully it'll be to your liking 🙂 

And I'm sorry, but in that commit I fixed the invalid face property as well! 😅 Thanks a lot for the PR though, I do appreciate any bug fixes and things you find and definitely welcome PRs.

**Comment by pqhieu** [comment]
Hey I just tried your fixes. Seems good to me. 
Thanks a lot for the works!

I will close this issue for now.
