### ISSUE TITLE
Add support for eyebrowse

### ISSUE THREAD

**Issue by spatz** [domtronn/spaceline-all-the-icons.el#56]
Like in spaceline: https://github.com/TheBB/spaceline#eyebrowse

**Comment by domtronn** [comment]
Hi @spatz, I don't personally use **Eyebrowse** so I'm not sure how it's meant to behave or how you'd like it represented in the modeline. I also have an issue open for **Perspective** as well _(#14)_ which feels very similar.

I can just port over the spaceline code if you want, but if there's any extra features/functionality you'd like out of it let me know 👍

**Comment by spatz** [comment]
Porting the spaceline code would be great, nothing more needed as far as I'm concerned.
Thanks!

**Comment by domtronn** [comment]
<img width="849" alt="screen shot 2017-08-24 at 11 09 18" src="https://user-images.githubusercontent.com/5881414/29661674-b3445d0e-88bc-11e7-813d-04132687751c.png">

I've started porting this over, and adding a little bit of iconization to the mode line _(see screenshot)_.  Workspace number **2** called **foobar**. What do you think?

I was going to make the displaying of the workspace name customisable/optional with `spaceline-all-the-icons-eyebrowse-display-name`.

Also, I've got it reusing the same icon set for `window-numbering` which you can see as it's eyebrowse window config #2 but I'm active in window #1... Would you prefer to have a separate icon set for `eyebrowse` compared to `window-number`? Do you use both of them at the same time?

Lastly, should the eyebrowse appear in _all_ windows, or just _active_ ones?

**Comment by spatz** [comment]
I do use both at the same time. I think they should be separately customizable but it's fine if the default is the same.

In spaceline the window number and window config number are shown as `n/m` or `n|m` (window, separator, window config) which I think is intuitive. You can show the name after or replace the window config number by the name if it's shown.

It should appear in all windows IMO.

**Comment by domtronn** [comment]
<img width="961" alt="screen shot 2017-08-24 at 11 38 06" src="https://user-images.githubusercontent.com/5881414/29662871-b6ec5386-88c0-11e7-9335-15fa34fbc8f7.png">

Cool, I've implemented all of that - Separate icons, reformatted to have the slot number first, then the workspace name :)

If you're happy, I'll release a new version with this in?

**Comment by spatz** [comment]
Looks awesome! Thanks!
