### ISSUE TITLE
How to change the background colour from "orange" to something else :)

### ISSUE THREAD

**Issue by dunkarooftop** [domtronn/spaceline-all-the-icons.el#57]
Thank you for the amazing work, I am wondering if there is a way to change the default "orange" colour to something else? Thanks

**Comment by domtronn** [comment]
Hi @dunkarooftop, sorry for the slow reply!

I assume you mean the colour of the mode line highlight? These are controlled by the following faces,

```el
'(
  ;; Active faces
  spaceline-highlight-face ;; The face that changes the highlighted part
  powerline-active1  ;; The face used for the second segment
  powerline active2  ;; The face used for the third segment
  mode-line  ;; The face used for the middle part of the mode line

  ;; Inactive faces
  powerline-inactive-1
  powerline-inactive-2
  mode-line-inactive
)
```

So if you want to change it from orange to a different colour, you could try

```el
(use-package spaceline-all-the-icons 
  :config
  (set-face-attribute 'spaceline-highlight-face :background "#3498db")) ;; For blue instead!
```

Hope this helps, if you have any more questions feel free to ask :)

**Comment by dunkarooftop** [comment]
Thank you... Those little icon you made possible make my eye happy.. :)

**Comment by dunkarooftop** [comment]
w
