### ISSUE TITLE
Fragmented clock separator

### ISSUE THREAD

**Issue by cmacrae** [domtronn/spaceline-all-the-icons.el#59]
Yo @domtronn! 👋 

Thanks for `spaceline-all-the-icons` - it really is very pretty.  

Got a tiny issue that's bugging me - admittedly more than it should be.  
On the right side of my modeline, where my clock sits: the separator is fragmented.  

Take a look:  
![](https://paste.xinu.at/JTT9Vt/)

Any ideas how I can fix this? Everything else looks so pristine!

Environment info:  
- Emacs version: `GNU Emacs 25.2.1 (x86_64-apple-darwin15.0.0, NS appkit-1404.13 Version 10.11.1 (Build 15B42)) of 2017-05-24` (from Nix)
- `spaceline-all-the-icons` package version: `20170719.131`
- `spaceline` package version: `20170630.2327`
- Theme: `doom-one` from [hlissner/emacs-doom-themes](https://github.com/hlissner/emacs-doom-themes)
- [Relevant part of Emacs config](https://github.com/cmacrae/.emacs.d/blob/master/emacs.org#theme) (see **Theme** & **Modeline**)

**Comment by justinbarclay** [comment]
Pretty sure this is duplicate of the issue I raised here:
https://github.com/domtronn/spaceline-all-the-icons.el/issues/47

**Comment by cmacrae** [comment]
@justinbarclay Ah, you're absolutely correct. I'll close this off and drop a note on the other issue 👍 
Cheers for bringing this to my attention.
