### ISSUE TITLE
all-the-icons-org-clock-current-task broke modeline for active buffer

### ISSUE THREAD

**Issue by spatz** [domtronn/spaceline-all-the-icons.el#60]
Commit f49ae9c7c6ed7001b7feffc6e03d51481ec67103 broke the modeline on the active buffer. Commenting it out solves the issue.

**Comment by domtronn** [comment]
That commit worked when I tested, and I don't use `org-clock` at all - But I've added a predicate to check that the variable is bound in the `:when` predicate 👍

**Comment by alexmurray** [comment]
Oops, sorry about that. FYI, org-clock-current-task is a variable so that should be boundp not fboundp

**Comment by domtronn** [comment]
You're right, thanks @alexmurray - I'll push that fix as well 😅 I can use `bound-and-true-p` which is a little more concise

**Comment by spatz** [comment]
You can't use a symbol with `bound-and-true-p`, need to simply pass the variable: `(bound-and-true-p org-clock-current-task)`.
