### ISSUE TITLE
`count-words` in `all-the-icons-region-info` is slow

### ISSUE THREAD

**Issue by jonathanj** [domtronn/spaceline-all-the-icons.el#67]
According to the profiler, the use of `count-words` in `spaceline-all-the-icons` is slow. The only place I could find this being used was the region info and unfortunately there's no way to turn it off. I'm quite happy to trade off word count in a region for speed.

![image](https://user-images.githubusercontent.com/112166/32106057-e6e55ae6-bb2a-11e7-8816-20a0e2265068.png)

For reasons I don't understand, this is significantly worse (bordering on unusable) when selecting a region of Python imports.

Would you be willing to make this feature customizable?

**Comment by domtronn** [comment]
You can disable the entire segment if you don't want to use it with

```el
(spaceline-toggle-all-the-icons-region-info-off)
```

But if you'd still like something to indicate that the region is active, let me know and I'll update this :)

**Comment by jonathanj** [comment]
Thanks, @domtronn, I didn't see that command. For my needs it's perfectly fine to turn off the region info altogether.
