### ISSUE TITLE
Gigantic icons

### ISSUE THREAD

**Issue by LefterisJP** [domtronn/spaceline-all-the-icons.el#76]
Hello!

I am in archlinux and installed the all the icons TTF package from the [AUR](https://aur.archlinux.org/packages/ttf-all-the-icons/).

Then I got the emacs package through el-get and installed it. It works but the modeline has some icons that are disproportionally big in size.

![2018-01-05-162509_792x691_scrot](https://user-images.githubusercontent.com/1658405/34615787-5da02278-f236-11e7-9b57-db9cf6f7fddf.png)

Any idea what can be done?

**Comment by LefterisJP** [comment]
Closing. This had to do with the way I installed the fonts. Something must be wrong with the AUR package I used. Doing `M-x all-the-icons-install-fonts` worked fine.

**Comment by alcarney** [comment]
I'm also experiencing this issue on Arch, however the problem persists even after doing
`M-x all-the-icons-install-fonts`

![2018-06-30-180320_1920x1080_scrot](https://user-images.githubusercontent.com/2675694/42127453-f0ff27e6-7c90-11e8-85b3-cf3967ba267d.png)
